version: "3.8"
services:
  api:
    image: ${IMAGE:-yourname/crisis-llm:gpu-latest}
    container_name: crisis_api
    ports: ["8000:8000"]
    volumes:
      - ./artifacts:/app/artifacts
    environment:
      - HF_HUB_DISABLE_TELEMETRY=1
    command: >
      sh -lc "python -m uvicorn ai_tweets.app.main:app
              --host 0.0.0.0 --port 8000 --workers 1"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
  ui:
    image: ${IMAGE:-yourname/crisis-llm:gpu-latest}
    container_name: crisis_ui
    depends_on: [api]
    ports: ["8501:8501"]
    volumes:
      - ./artifacts:/app/artifacts
    environment:
      - API_URL=http://localhost:8000
    command: >
      sh -lc "streamlit run src/ai_tweets/streamlit_app.py
              --server.address=0.0.0.0 --server.port=8501"
