[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "disaster-tweets-llm-pro"
version = "0.1.0"
description = "Disaster Tweets LLM — production scaffold"
readme = "README.md"
requires-python = ">=3.9"
authors = [{name="Your Team"}]
dependencies = [
  "transformers>=4.40.0",
  "datasets>=2.19.0",
  "torch>=2.1.0",
  "scikit-learn>=1.2.0",
  "fastapi>=0.110.0",
  "uvicorn>=0.29.0",
  "pydantic>=2.6.0",
  "prometheus-client>=0.20.0",
  "typer[all]>=0.12.0",
  "rich>=13.7.0",
  "evaluate>=0.4.1",
  "pandas>=2.0.0",
  "pyyaml>=6.0.0"
]

[project.scripts]
ai-tweets = "ai_tweets.cli:app"
