seed: 42
model_name: distilbert-base-uncased
max_length: 256
epochs: 3
batch_size: 16
learning_rate: 5e-5
weight_decay: 0.01
warmup_ratio: 0.1
output_dir: artifacts/model
metrics_path: artifacts/metrics.json
